### ISSUE TITLE
[BUG] Random Promoted content in Tweet Details

### ISSUE THREAD

**Issue by JasonKhew96** [Dr-TSNG/TwiFucker#19]

**Comment by GalaxyNight** [comment]
same

**Comment by AlDollaz** [comment]
Seeing the same thing.

**Comment by AllyGravyKun** [comment]
Still seeing the same thing! This module would be perfection if it took care of this. 👍🏾

**Comment by JasonKhew96** [comment]
probably fixed in https://github.com/Dr-TSNG/TwiFucker/commit/8f24da692e098787726b732523f8c4ed35a17ada

**Comment by Bec-de-Xorbin** [comment]
I can still see those randomly, unfortunately.

**Comment by aliafshany** [comment]
i can confirm that i see those in tweets that got replies in it.
but the timeline itself is clear

**Comment by aliafshany** [comment]
Update:
i still get ads in comments even in V 1.4 which just released

**Comment by Dr-TSNG** [comment]
@aliafshany You might clear Twitter data first

**Comment by aliafshany** [comment]
@Dr-TSNG 
i did that but it didn't help.
this is a video demo of what happened.

https://user-images.githubusercontent.com/40741745/182552862-b0a5c663-e4e9-4cf0-bdf2-1f8e445aaa67.mp4

**Comment by fatguy666** [comment]
@aliafshany did you try with legacy hook on?

I went onto that same comment and didn't see anything. Can't post video here (dunno why) so replied to the Twitter post. 

I'm using AeroWitter 1.1 + TwiFucker 1.4 btw.

**Comment by aliafshany** [comment]
@fatguy666 
yes i tried still the same
and also i saw your video, you didn't mention me at all there :))
- you can't pst it here because of its size

**Comment by JasonKhew96** [comment]
try this build, should be fixed, this kind of ads is hard to catch in my Twitter account.
https://github.com/Dr-TSNG/TwiFucker/commit/6dd0747bcf96fb08aa683a509df31758cadbe0d1

**Comment by JasonKhew96** [comment]
apparently, last commit does nothing, try next commit
https://github.com/Dr-TSNG/TwiFucker/commit/814b66a80b4b4b13f59fcccb14d5e18e35f1a33f again

**Comment by Bec-de-Xorbin** [comment]
It's almost perfect now, thank you. Still, once in a while, promoted tweet is shown.
